///////////////////////////////////////////////////////////////////////////////
// M_QPopt.cpp
#include "TcPch.h"
#pragma hdrstop

#include "M_QPopt.h"
#include "QPoptVersion.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif
DEFINE_THIS_FILE()

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module CM_QPopt
BEGIN_INTERFACE_MAP(CM_QPopt)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
	INTERFACE_ENTRY(IID_ITcWatchSource, ITcWatchSource)
///<AutoGeneratedContent id="InterfaceMap">
	INTERFACE_ENTRY(IID_I_QPopt, I_QPopt)
///</AutoGeneratedContent>
END_INTERFACE_MAP()

IMPLEMENT_IPERSIST_LIB(CM_QPopt, VID_QPopt, CID_QPoptCM_QPopt)
IMPLEMENT_ITCOMOBJECT(CM_QPopt)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP2(CM_QPopt)
IMPLEMENT_ITCADI(CM_QPopt)
IMPLEMENT_ITCWATCHSOURCE(CM_QPopt)

///////////////////////////////////////////////////////////////////////////////
// Set parameters of CM_QPopt 
BEGIN_SETOBJPARA_MAP(CM_QPopt)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of CM_QPopt 
BEGIN_GETOBJPARA_MAP(CM_QPopt)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
///</AutoGeneratedContent>
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get watch entries of CM_QPopt
BEGIN_OBJPARAWATCH_MAP(CM_QPopt)
	OBJPARAWATCH_DATAAREA_MAP()
///<AutoGeneratedContent id="ObjectParameterWatchMap">
///</AutoGeneratedContent>
END_OBJPARAWATCH_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of CM_QPopt
BEGIN_OBJDATAAREA_MAP(CM_QPopt)
///<AutoGeneratedContent id="ObjectDataAreaMap">
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()


///////////////////////////////////////////////////////////////////////////////
// Constructor
CM_QPopt::CM_QPopt()
{
///<AutoGeneratedContent id="MemberInitialization">
///</AutoGeneratedContent>
}

///////////////////////////////////////////////////////////////////////////////
// Destructor
CM_QPopt::~CM_QPopt() 
{
}

///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(CM_QPopt)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters 
// Allocate memory
HRESULT CM_QPopt::SetObjStatePS(PTComInitDataHdr pInitData)
{
	HRESULT hr = S_OK;
	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);

	// Initialize QP solver
	// set up OSQP matrices
	m_P = (OSQPCscMatrix*)std::malloc(sizeof(OSQPCscMatrix));
	m_A = (OSQPCscMatrix*)std::malloc(sizeof(OSQPCscMatrix));
	// set matrices with CSC format
	csc_set_data(m_P, m_nVars, m_nVars, m_P_nnz, m_P_x, m_P_i, m_P_p);
	csc_set_data(m_A, m_nCons, m_nVars, m_A_nnz, m_A_x, m_A_i, m_A_p);

	/* Set default settings */
	m_osqp_settings = (OSQPSettings*)std::malloc(sizeof(OSQPSettings));
	/* // see https://osqp.org/docs/interfaces/solver_settings.html // */
	if (m_osqp_settings) {
		osqp_set_default_settings(m_osqp_settings);

		m_osqp_settings->polishing = 0;
		m_osqp_settings->polish_refine_iter = 3;
		m_osqp_settings->scaled_termination = 0;
		m_osqp_settings->scaling = 10;
		m_osqp_settings->max_iter = 25;
	}

	/* Setup solver */
	m_exitflag = osqp_setup(&m_solver, m_P, m_q, m_A, m_lb, m_ub, m_nCons, m_nVars, m_osqp_settings);

	// init solve as warm start
	if (!m_exitflag) {
		m_exitflag = osqp_solve(m_solver);
	}


	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT CM_QPopt::SetObjStateSO()
{
	HRESULT hr = S_OK;
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT CM_QPopt::SetObjStateOS()
{
	HRESULT hr = S_OK;
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
HRESULT CM_QPopt::SetObjStateSP()
{
	HRESULT hr = S_OK;
	return hr;
}

///<AutoGeneratedContent id="ImplementationOf_I_QPopt">
HRESULT CM_QPopt::solve(double* in1, double* out1)
{
	//out1[0] = -2 * in1[0];

	// solve
	m_exitflag = osqp_solve(m_solver);

	// Write solution to output
	for (int i = 0; i < m_nVars; ++i) {
		out1[i] = m_solver->solution->x[i];
	}

	HRESULT hr = S_OK;
	return hr;
}
///</AutoGeneratedContent>
