///////////////////////////////////////////////////////////////////////////////
// M_QPopt.h
#pragma once

#include "QPoptInterfaces.h"

#include "osqp/osqp.h"

class CM_QPopt 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public I_QPopt
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST_LIB()
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CM_QPopt();
	virtual	~CM_QPopt();

///<AutoGeneratedContent id="InterfaceMembers">
	// I_QPopt
	virtual HRESULT TCOMAPI solve(double* in1, double* out1);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();



	// Custom member variables for QSQP solver

	// number of optimization variables 
	static const OSQPInt m_nVars = 8;
	// number of constraints 
	static const OSQPInt m_nCons = 22;
	// CSC representation of P matrix 
	OSQPCscMatrix* m_P;
	// Notice: Only take the upper triangular representation, i.e.  P = numpy.triu(P) 
	OSQPFloat m_P_x[8] = { 0.0005, 0.0005, 0.0005, 0.0005, 0.0005, 0.0005, 0.0005, 0.0005 };
	OSQPInt m_P_nnz = 8;
	OSQPInt m_P_i[8] = { 0, 1, 2, 3, 4, 5, 6, 7 };
	OSQPInt m_P_p[9] = { 0, 1, 2, 3, 4, 5, 6, 7, 8 };

	// CSC representation of A matrix 
	OSQPCscMatrix* m_A;
	// Notice: All elements of A are stored 
	OSQPFloat m_A_x[64] = { -0.618537, 0.459121, 0.637667, 0.03826, 0.03826, 0.00956501, 1.0, -1.0, 0.618537, 0.459121, 0.637667, 0.03826, -0.03826, -0.00956501, 1.0, -1.0, 0.618537, -0.459121, 0.637667, -0.03826, -0.03826, 0.00956501, 1.0, -1.0, -0.618537, -0.459121, 0.637667, -0.03826, 0.03826, -0.00956501, 1.0, -1.0, -0.618537, 0.459121, -0.637667, -0.03826, -0.03826, 0.00956501, 1.0, -1.0, 0.618537, 0.459121, -0.637667, -0.03826, 0.03826, -0.00956501, 1.0, -1.0, 0.618537, -0.459121, -0.637667, 0.03826, 0.03826, 0.00956501, 1.0, -1.0, -0.618537, -0.459121, -0.637667, 0.03826, -0.03826, -0.00956501, 1.0, -1.0 };
	OSQPInt m_A_nnz = 64;
	OSQPInt m_A_i[64] = { 0, 1, 2, 3, 4, 5, 6, 14, 0, 1, 2, 3, 4, 5, 7, 15, 0, 1, 2, 3, 4, 5, 8, 16, 0, 1, 2, 3, 4, 5, 9, 17, 0, 1, 2, 3, 4, 5, 10, 18, 0, 1, 2, 3, 4, 5, 11, 19, 0, 1, 2, 3, 4, 5, 12, 20, 0, 1, 2, 3, 4, 5, 13, 21 };
	OSQPInt m_A_p[9] = { 0, 8, 16, 24, 32, 40, 48, 56, 64 };
	// dense vector q 
	OSQPFloat m_q[8] = { -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1 };
	// dense lower bound vector lb 
	OSQPFloat m_lb[22] = { 5, -5, -10, 0, 0, 0, 50, 50, 50, 50, 50, 50, 50, 50, -500, -500, -500, -500, -500, -500, -500, -500 };
	// dense upper bound vector ub 
	OSQPFloat m_ub[22] = { 5, -5, -10, 0, 0, 0, 500, 500, 500, 500, 500, 500, 500, 500, -50, -50, -50, -50, -50, -50, -50, -50 };
	// Exitflag  
	OSQPInt m_exitflag;
	// Solver, settings, matrices  
	OSQPSolver* m_solver;
	OSQPSettings* m_osqp_settings;



///<AutoGeneratedContent id="Members">
///</AutoGeneratedContent>
};
