///////////////////////////////////////////////////////////////////////////////
// QPoptServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_QPopt = 0x3F000000;
#define SRVNAME_QPOPT "QPopt"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_QPoptCM_QPopt = {0xe0c0c32a,0x147b,0x4524,{0x98,0x42,0xe1,0xad,0x0b,0xfe,0xdc,0x61}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
#if !defined(_TC_IID_62AD4421_E531_40B8_A0B4_01255FA59EC4_INCLUDED_)
#define _TC_IID_62AD4421_E531_40B8_A0B4_01255FA59EC4_INCLUDED_
TCOM_DECL_INTERFACE("62ad4421-e531-40b8-a0b4-01255fa59ec4", I_QPopt)
#endif // !defined(_TC_IID_62AD4421_E531_40B8_A0B4_01255FA59EC4_INCLUDED_)

///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
