///////////////////////////////////////////////////////////////////////////////
// QPoptClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "QPoptClassFactory.h"
#include "QPoptServices.h"
#include "QPoptVersion.h"
#include "M_QPopt.h"

BEGIN_CLASS_MAP(CQPoptClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_QPopt, CID_QPoptCM_QPopt, SRVNAME_QPOPT "!CM_QPopt", CM_QPopt)
///</AutoGeneratedContent>
END_CLASS_MAP()

CQPoptClassFactory::CQPoptClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_QPOPT));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(QPopt));
#endif //defined(TCDBG_UNIT_VERSION)
}

