///////////////////////////////////////////////////////////////////////////////
// QPoptInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "QPoptServices.h"

///<AutoGeneratedContent id="Interfaces">
#if !defined(_TC_TYPE_62AD4421_E531_40B8_A0B4_01255FA59EC4_INCLUDED_)
#define _TC_TYPE_62AD4421_E531_40B8_A0B4_01255FA59EC4_INCLUDED_
struct __declspec(novtable) I_QPopt : public ITcUnknown
{
	virtual HRESULT TCOMAPI solve(double* in1, double* out1)=0;
};
_TCOM_SMARTPTR_TYPEDEF(I_QPopt, IID_I_QPopt);
#endif // !defined(_TC_TYPE_62AD4421_E531_40B8_A0B4_01255FA59EC4_INCLUDED_)

///</AutoGeneratedContent>
